package zsbpj.lccpj.sql;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig t_JC_LOGININFODaoConfig;

    private final T_JC_LOGININFODao t_JC_LOGININFODao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        t_JC_LOGININFODaoConfig = daoConfigMap.get(T_JC_LOGININFODao.class).clone();
        t_JC_LOGININFODaoConfig.initIdentityScope(type);

        t_JC_LOGININFODao = new T_JC_LOGININFODao(t_JC_LOGININFODaoConfig, this);

        registerDao(T_JC_LOGININFO.class, t_JC_LOGININFODao);
    }
    
    public void clear() {
        t_JC_LOGININFODaoConfig.getIdentityScope().clear();
    }

    public T_JC_LOGININFODao getT_JC_LOGININFODao() {
        return t_JC_LOGININFODao;
    }

}
