package zsbpj.lccpj.sql;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table T__JC__LOGININFO.
 */
public class T_JC_LOGININFO implements Serializable {

    private Long ids;
    private String id;
    private String un;
    private String ui;
    private String dc;
    private String dd;
    private String uf;
    private String url;

    public T_JC_LOGININFO() {
    }

    public T_JC_LOGININFO(Long ids) {
        this.ids = ids;
    }

    public T_JC_LOGININFO(Long ids, String id, String un, String ui, String dc, String dd, String uf, String url) {
        this.id = id;
        this.ids = ids;
        this.un = un;
        this.ui = ui;
        this.dc = dc;
        this.dd = dd;
        this.uf = uf;
        this.url = url;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Long getIds() {
        return ids;
    }

    public void setIds(Long ids) {
        this.ids = ids;
    }

    public String getUn() {
        return un;
    }

    public void setUn(String un) {
        this.un = un;
    }

    public String getUi() {
        return ui;
    }

    public void setUi(String ui) {
        this.ui = ui;
    }

    public String getDc() {
        return dc;
    }

    public void setDc(String dc) {
        this.dc = dc;
    }

    public String getDd() {
        return dd;
    }

    public void setDd(String dd) {
        this.dd = dd;
    }

    public String getUf() {
        return uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
