package com.lcc.db.test;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table USER_INFO.
 */
public class UserInfo implements Serializable {

    private Long id;
    private String phone;
    private String nickname;
    private String xb;
    private String email;
    private String created_at;
    private String jf;
    private String qm;
    private String zy;
    private String user_image;
    private String gz_num;
    private String fs_num;

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }


    public UserInfo(Long id, String phone, String nickname, String xb, String email,
                    String created_at, String jf,
                    String qm, String zy, String user_image, String gz_num, String fs_num) {
        this.id = id;
        this.phone = phone;
        this.nickname = nickname;
        this.xb = xb;
        this.email = email;
        this.created_at = created_at;
        this.jf = jf;
        this.qm = qm;
        this.zy = zy;
        this.user_image = user_image;
        this.gz_num = gz_num;
        this.fs_num = fs_num;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getXb() {
        return xb;
    }

    public void setXb(String xb) {
        this.xb = xb;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getJf() {
        return jf;
    }

    public void setJf(String jf) {
        this.jf = jf;
    }

    public String getQm() {
        return qm;
    }

    public void setQm(String qm) {
        this.qm = qm;
    }

    public String getZy() {
        return zy;
    }

    public void setZy(String zy) {
        this.zy = zy;
    }

    public String getUser_image() {
        return user_image;
    }

    public void setUser_image(String user_image) {
        this.user_image = user_image;
    }


    public String getGz_num() {
        return gz_num;
    }

    public void setGz_num(String gz_num) {
        this.gz_num = gz_num;
    }

    public String getFs_num() {
        return fs_num;
    }

    public void setFs_num(String fs_num) {
        this.fs_num = fs_num;
    }
}
